// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAav5gqa7Z7RJXTGdttkXjJrl0fckAhKsY',
    appId: '1:287981048572:web:6154d7180c24a8e2cdbd79',
    messagingSenderId: '287981048572',
    projectId: 'personal-trainer-finder-app',
    authDomain: 'personal-trainer-finder-app.firebaseapp.com',
    storageBucket: 'personal-trainer-finder-app.firebasestorage.app',
    measurementId: 'G-R9BVDPSSBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsIe5yvPHxtQYtz8ZtDGFjyNmMWKMV-LU',
    appId: '1:287981048572:android:7fbfa5fbe2e7c7d4cdbd79',
    messagingSenderId: '287981048572',
    projectId: 'personal-trainer-finder-app',
    storageBucket: 'personal-trainer-finder-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLnQY5fPP5cmtkSAThbgf5vZwYtxLZzQ',
    appId: '1:287981048572:ios:1c02a2fbe3384964cdbd79',
    messagingSenderId: '287981048572',
    projectId: 'personal-trainer-finder-app',
    storageBucket: 'personal-trainer-finder-app.firebasestorage.app',
    iosBundleId: 'com.example.trainerFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLnQY5fPP5cmtkSAThbgf5vZwYtxLZzQ',
    appId: '1:287981048572:ios:1c02a2fbe3384964cdbd79',
    messagingSenderId: '287981048572',
    projectId: 'personal-trainer-finder-app',
    storageBucket: 'personal-trainer-finder-app.firebasestorage.app',
    iosBundleId: 'com.example.trainerFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAav5gqa7Z7RJXTGdttkXjJrl0fckAhKsY',
    appId: '1:287981048572:web:5ec26eed63e59708cdbd79',
    messagingSenderId: '287981048572',
    projectId: 'personal-trainer-finder-app',
    authDomain: 'personal-trainer-finder-app.firebaseapp.com',
    storageBucket: 'personal-trainer-finder-app.firebasestorage.app',
    measurementId: 'G-41HCBC0JQJ',
  );
}
